# Generated by Django 4.2.6 on 2023-10-23 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dead_line",
                    models.DateTimeField(
                        blank=True,
                        help_text="Enter the deadline date as you wish!",
                        null=True,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("tags", models.ManyToManyField(to="tasks.tag")),
            ],
        ),
    ]
